cabal-version:   3.16
name:            Axiom
version:         0.1.0.0
license:         NONE
author:          torkay
maintainer:      amatorri847@gmail.com
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall -O2

executable Axiom
    import:           warnings
    main-is:          Main.hs
    other-modules:    Axiom.World,
                      Axiom.Geo.Elevation,
                      Axiom.Geo.Noise,
                      Axiom.Geo.Flow,
                      Axiom.Geo.Drainage,
                      Axiom.Types.Hydrology,
                      Axiom.Geo.Hydrology,
                      Axiom.Climate.Temperature
    build-depends:    base >=4.18,
                      massiv >= 1.0.5.0,
                      pure-noise,
                      vector,
                      deepseq,
                      fgl >= 5.8.3.0,
                      PSQueue >= 1.2.1,
                      containers
    hs-source-dirs:   src
    default-language: GHC2021
